heat_template_version: "2015-04-30"

description: Deployment stack.

parameters:

  seed_ip:
    type: string
    label: Seed IP
    description: The floating IP for the instance.

  seed_volume:
    type: string
    label: Seed Volume
    description: The block storage volume for the instance

  seed_instance:
    type: string
    label: Seed instance
    description: The instance

resources:

  seed_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_param: seed_instance }
      volume_id: { get_param: seed_volume }
      mountpoint: /dev/vbd

  seed_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      server_id: { get_param: seed_instance }
      floating_ip: { get_param: seed_ip }
