AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys a seed instance to the seed infrastructure

Mappings:

  AMI:
    eu-west-1:
      coreos: ami-80e1bae6
      linux: ami-70edb016

Parameters:

  ResourcesStack:
    Type: String
    Description: The resources for the seed infrastructure.

  NetworkStack:
    Type: String
    Description: The seed network into which to deploy.

  UserData:
    Type: String
    Description: The user data to user for the instance

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: io-stuartw-seed
    Description: The keypair to use to connect to the instance.

  InstanceType:
    Type: String
    Default: t2.micro
    Description: The instance type to launch.

Resources:

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Fn::ImportValue: !Sub ${NetworkStack}:role
      Path: /

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AMI, !Ref "AWS::Region", coreos]
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStack}:subnet
      Volumes:
      - Device: /dev/sdk
        VolumeId:
          Fn::ImportValue: !Sub ${ResourcesStack}:volume
      SecurityGroupIds:
      - Fn::ImportValue: !Sub ${NetworkStack}:outbound-internet-http-sg
      - Fn::ImportValue: !Sub ${NetworkStack}:inbound-jenkins-admin-sg
      - Fn::ImportValue: !Sub ${NetworkStack}:inbound-ssh-sg
      UserData:
        Fn::Base64: !Ref UserData
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-instance

  IpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Instance
      AllocationId:
        Fn::ImportValue: !Sub ${ResourcesStack}:ip

Outputs:

  Instance:
    Description: The seed instance.
    Value: !Ref Instance
    Export:
      Name: !Sub ${AWS::StackName}:instance
