heat_template_version: "2015-04-30"

description: Deployment stack.

parameters:

  seed_keypair:
    type: string
    label: Seed keypair
    description: The keypair to use to connect to the instance.

  seed_network:
    type: string
    label: Seed network
    description: The seed network into which to deploy.

  seed_user_data:
    type: string
    label: Seed user data
    description: The user data to user for the instance

resources:

  seed_instance:
    type: OS::Nova::Server
    properties:
      name: main.seed.stuartw.io
      key_name: { get_param: seed_keypair }
      flavor: 1C-1GB
      image: CoreOS 1068.9.0
      networks:
      - network: { get_param: seed_network }
      user_data: { get_param: seed_user_data }
      user_data_format: RAW
      security_groups:
      - seed-jenkins-admin
      - seed-jenkins-internet
      - seed-ssh

outputs:

  seed_instance:
    description: The seed instance.
    value: { get_resource: seed_instance }
