heat_template_version: "2015-04-30"

description: Deployment stack.

parameters:

  seed_keypair:
    type: string
    label: Seed keypair
    description: The keypair to use to connect to the instance.

  seed_network:
    type: string
    label: Seed network
    description: The seed network into which to deploy.

  seed_ip:
    type: string
    label: Seed IP
    description: The floating IP for the instance.

  seed_volume:
    type: string
    label: Seed Volume
    description: The block storage volume for the instance

  seed_user_data:
    type: string
    label: Seed User Data
    description: The user data to use to initialise the instance.

resources:

  seed_instance:
    type: OS::Nova::Server
    properties:
      name: main.seed.stuartw.io
      key_name: { get_param: seed_keypair }
      flavor: 1C-1GB
      image: CoreOS 1068.9.0
      networks:
      - network: { get_param: seed_network }
        floating_ip: { get_param: seed_ip }
      user_data: { get_param: seed_user_data }
      user_data_format: RAW
      security_groups:
      - seed-jenkins-admin
      - seed-jenkins-internet
      - seed-ssh

  seed_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: seed_instance }
      volume_id: { get_param: seed_volume }
      mountpoint: /dev/vbd

  seed_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_param: seed_ip }
      server_id: { get_resource: seed_instance }
