heat_template_version: "2015-04-30"

description: Network stack.

parameters:

  external_network:
    type: string
    label: External network
    description: The external network to which to attach.

resources:

  seed_network:
    type: OS::Neutron::Net
    properties:
      name: seed.stuartw.io

  seed_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: main.subnet.seed.stuartw.io
      network: { get_resource: seed_network }
      cidr: 10.0.1.0/24
      gateway_ip: 10.0.1.1
      ip_version: 4

  seed_router:
    type: OS::Neutron::Router
    properties:
      name: router.seed.stuartw.io
      external_gateway_info:
        network: { get_param: external_network }

  seed_router_subnet_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: seed_router }
      subnet: { get_resource: seed_subnet }

  seed_jenkins_admin_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: seed-jenkins-admin
      description: Security group for Jenkins administration access.
      rules:
      - direction: ingress
        port_range_min: 8080
        port_range_max: 8080
        protocol: tcp
        remote_ip_prefix: 86.11.0.0/16

  seed_jenkins_internet_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: seed-jenkins-internet
      description: Security group for Jenkins internet access.
      rules:
      - direction: egress
        port_range_min: 80
        port_range_max: 80
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
      - direction: egress
        port_range_min: 443
        port_range_max: 443
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0

  seed_ssh_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: seed-ssh
      description: Security group for SSH access.
      rules:
      - direction: ingress
        port_range_min: 22
        port_range_max: 22
        protocol: tcp
        remote_ip_prefix: 86.11.0.0/16

  seed_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }

outputs:

  seed_network:
    description: The seed network.
    value: { get_resource: seed_network }

  seed_subnet:
    description: The seed subnet.
    value: { get_resource: seed_subnet }

  seed_ip:
    description: The floating IP for the main seed server.
    value: { get_resource: seed_ip }