AWSTemplateFormatVersion: "2010-09-09"

Description: Persistent resources for the seed infrastructure

Mappings:

  AvailabilityZone:
    eu-west-1:
      a: eu-west-1a
    eu-west-2:
      a: eu-west-2a

Parameters:

  VolumeType:
    Type: String
    Default: gp2
    Description: The type of volume to use for the seed infrastructure

Resources:

  Ip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !FindInMap [AvailabilityZone, !Ref "AWS::Region", a]
      VolumeType: !Ref VolumeType
      Size: 50
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-volume

Outputs:

  Ip:
    Description: The floating IP for the main seed server.
    Value: !GetAtt Ip.AllocationId
    Export:
      Name: !Sub ${AWS::StackName}:ip

  Volume:
    Description: The seed volume.
    Value: !Ref Volume
    Export:
      Name: !Sub ${AWS::StackName}:volume
