AWSTemplateFormatVersion: "2010-09-09"

Description: Long term storage for the seed infrastructure

Parameters:

  GitBucketPrefix:
    Type: String
    Default: io-stuartw-seed
    Description: The S3 bucket name to use for git storage

Resources:

  GitBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${GitBucketPrefix}-git
      VersioningConfiguration:
        Status: Enabled
