heat_template_version: "2015-04-30"

description: Resources stack.

resources:

  seed_git_container:
    type: OS::Swift::Container
    properties:
      name: seed-git
      PurgeOnDelete: false

  seed_git_history_container:
    type: OS::Swift::Container
    properties:
      name: seed-git-history
      PurgeOnDelete: false

  seed_volume:
    type: OS::Cinder::Volume
    properties:
      name: seed
      description: Block storage volume for the main seed server.
      multiattach: false
      size: 50

outputs:

  seed_volume:
    description: Block storage volume for the main seed server.
    value: { get_resource: seed_volume }
