AWSTemplateFormatVersion: "2010-09-09"

Description: Long term storage for the seed infrastructure

Parameters:

  GitBucketName:
    Type: String
    Default: io-stuartw-seed-git
    Description: The S3 bucket name to use for git storage

Resources:

  GitBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref GitBucketName
      VersioningConfiguration:
        Status: Enabled
